# Numpy

Numpy is a general-purpose array processing package.

It provides a high-performance multidimensional array object and tools for working with these arrays.

It is the fundamental package for scientific computing with python.

## Operations using NumPy

The following operations can be performed using NumPy:
    
> Mathematical and logical operators on arrays.

> Fourier transforms and routines for shape manipulation.

> Operations related to linear algebra. NumPy has in-built functions for linear algebra and random number generation.

## NumPy - A Replacement for MatLab

NumPy is often used along with packages like Scipy(Scientific Python) and Mat-plotlob(plotting library).

This combination is widely used as a replacement for Matlab, a popular platform for technical computing.

However, Python alternative to Matlab is now seen as a more modern and complete programming language.

### Is NumPy faster than Python lists?

As an array it is a collection of homogeneous data-types that are stored in contiguous memory locations.

The NumPy package breaks down a task into multiple fragments and the processes all the fragments parallely.

The NumPy package integrates C, C++ and Fortran codes in python\. These programming languages have very little execution time compared to Python.

_Let's Code-in_

In [1]:
# First things first - Import the package 
import numpy as np

### Create a Matrix

In [2]:
mylist = [1,2,3,4,5]
arr = np.array(mylist)
print('List')
print(mylist)
print(type(mylist))
print()
print('NumPy array')
print(arr)
print(type(arr))

List
[1, 2, 3, 4, 5]
<class 'list'>

NumPy array
[1 2 3 4 5]
<class 'numpy.ndarray'>


linspace generates data in equitable distance between them

In [3]:
np.linspace(1,10)

array([ 1.        ,  1.18367347,  1.36734694,  1.55102041,  1.73469388,
        1.91836735,  2.10204082,  2.28571429,  2.46938776,  2.65306122,
        2.83673469,  3.02040816,  3.20408163,  3.3877551 ,  3.57142857,
        3.75510204,  3.93877551,  4.12244898,  4.30612245,  4.48979592,
        4.67346939,  4.85714286,  5.04081633,  5.2244898 ,  5.40816327,
        5.59183673,  5.7755102 ,  5.95918367,  6.14285714,  6.32653061,
        6.51020408,  6.69387755,  6.87755102,  7.06122449,  7.24489796,
        7.42857143,  7.6122449 ,  7.79591837,  7.97959184,  8.16326531,
        8.34693878,  8.53061224,  8.71428571,  8.89795918,  9.08163265,
        9.26530612,  9.44897959,  9.63265306,  9.81632653, 10.        ])

In [4]:
np.linspace(1,10,5)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

Dimensions

In [5]:
arr.ndim

1

Size

In [6]:
arr.size

5

Shape

In [7]:
arr.shape

(5,)

dtype

In [8]:
arr.dtype

dtype('int32')

itemsize

In [9]:
arr.itemsize # since, dtype is int32 it equals to 4 bytes

4

### 2-D Matrix

In [10]:
mylist2 = [[1,2,3],[4,5,6],[7,8,9]]
print(mylist2)

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]


In [11]:
arr2 = np.array(mylist2)
print(arr2)
print(arr2.ndim)
print(arr2.shape)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
2
(3, 3)


In [12]:
n3 = np.arange(10)
n3

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
n3.reshape(5,2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [14]:
n3.reshape(-1,2)
# This means it will reshape till it's ability to create a matrix with 2 columns and rows based on number of elements

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

#### Random seed

Numpy random seed is a function that sets the seed for generating random numbers.

Specifying the seed value ensures the sequence of random numbers generated remains the same across multiple runs.

In [15]:
np.random.seed(23)

In [16]:
n34 = np.random.randint(low=10,high=100,size=(3,4))
n34

array([[93, 50, 83, 64],
       [41, 86, 49, 35],
       [61, 16, 55, 22]])

In [17]:
n43 = np.random.randint(low=10,high=100,size=12)
n43

array([59, 76, 85, 95, 79, 74, 22, 31, 58, 51, 89, 72])

In [18]:
n43.reshape(4,3)

array([[59, 76, 85],
       [95, 79, 74],
       [22, 31, 58],
       [51, 89, 72]])

In [19]:
np.random.randn(2,4) # randomly generates numbers for 2 rows and 4 columns

array([[ 1.11872163,  0.80399214, -1.84926796,  1.38809014],
       [-2.41201527, -0.45175246,  1.17420672,  0.76634838]])

In [20]:
np.random.randint(2,5,(5,5)) # numbers between 2 and 5 of shape 5 x 5

array([[4, 4, 3, 4, 4],
       [2, 3, 2, 2, 3],
       [2, 4, 4, 4, 4],
       [2, 3, 4, 2, 4],
       [2, 2, 4, 4, 2]])

### Operations on Arrays

In [21]:
n6a = np.arange(1,7,2)
n6b = np.arange(11,17,2)

print(n6a)
print(n6b)

[1 3 5]
[11 13 15]


In [22]:
n6a+n6b

array([12, 16, 20])

In [23]:
n34a = np.arange(1,13).reshape(3,4)
n34b = np.arange(21,33).reshape(3,4)

print(n34a)
print()
print(n34b)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

[[21 22 23 24]
 [25 26 27 28]
 [29 30 31 32]]


In [24]:
n34a+n34b

array([[22, 24, 26, 28],
       [30, 32, 34, 36],
       [38, 40, 42, 44]])

In [25]:
n34a*n34b

array([[ 21,  44,  69,  96],
       [125, 156, 189, 224],
       [261, 300, 341, 384]])

In [26]:
n34a/n34b

array([[0.04761905, 0.09090909, 0.13043478, 0.16666667],
       [0.2       , 0.23076923, 0.25925926, 0.28571429],
       [0.31034483, 0.33333333, 0.35483871, 0.375     ]])

In [27]:
n43 = np.arange(21,33).reshape(4,3)
n43

array([[21, 22, 23],
       [24, 25, 26],
       [27, 28, 29],
       [30, 31, 32]])

In [28]:
n34a@n43 # dot product

array([[ 270,  280,  290],
       [ 678,  704,  730],
       [1086, 1128, 1170]])

 ### Access

#### We pass index numbers to access and operate with arrays or matrices

In [29]:
n79 = np.random.randint(low=10,high=100,size=(7,9))
n79

array([[80, 76, 92, 95, 65, 37, 72, 53, 84],
       [81, 52, 93, 31, 16, 78, 32, 53, 18],
       [95, 72, 42, 70, 21, 11, 51, 36, 47],
       [51, 66, 49, 91, 42, 63, 45, 33, 39],
       [52, 48, 14, 42, 60, 95, 37, 43, 44],
       [10, 21, 72, 98, 64, 99, 88, 51, 80],
       [95, 15, 17, 14, 26, 19, 66, 58, 53]])

Zeroth Row

In [30]:
n79[0]

array([80, 76, 92, 95, 65, 37, 72, 53, 84])

In [31]:
# Just some free style fetches

n79[2:,2] # fetch in 3nd row  and 3rd column

array([42, 49, 14, 72, 17])

In [32]:
n79[0:4,:5] # first 4 rows and first 5 columns

array([[80, 76, 92, 95, 65],
       [81, 52, 93, 31, 16],
       [95, 72, 42, 70, 21],
       [51, 66, 49, 91, 42]])

In [33]:
# stepped fetch

n79[0:6:2,1:5:3]

# Row
# starts from 1st row skips two rows and ends at 6th row

# column
# starts from 2nd column skips 3 columns and ends at 5th column

# Row to column movement
# 1st row - 2nd column
# 1st row - 5th column

# 3rd row - 2nd column
# 3rd row - 5th column

# 5th row - 2nd column
# 5th row - 5th column

array([[76, 65],
       [72, 21],
       [48, 60]])

vector

In [34]:
n79[[1,2,3]] # first, second and third row

array([[81, 52, 93, 31, 16, 78, 32, 53, 18],
       [95, 72, 42, 70, 21, 11, 51, 36, 47],
       [51, 66, 49, 91, 42, 63, 45, 33, 39]])

In [35]:
n79[[1,2],[1,2]] # n[[row],[col]]

array([52, 42])

In [36]:
list(zip([1,2],[3,4]))

[(1, 3), (2, 4)]

In [37]:
np.fromfunction(lambda i,j: i==j,(5,5))

array([[ True, False, False, False, False],
       [False,  True, False, False, False],
       [False, False,  True, False, False],
       [False, False, False,  True, False],
       [False, False, False, False,  True]])

#### Matrix

In [38]:
arr2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [39]:
mat = np.mat(arr2)
mat

matrix([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [40]:
type(np.mat(arr2))

numpy.matrix

In [41]:
mylist

[1, 2, 3, 4, 5]

In [42]:
np.asarray(mylist)

array([1, 2, 3, 4, 5])

In [43]:
np.asanyarray(mylist)

array([1, 2, 3, 4, 5])

In [44]:
np.asanyarray(mat)

# Here, it doesn't get converted to array because matrix belongs to the family array and "any" inhibits that feature.

matrix([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [45]:
# On the other hand, asarray converts matrix to an array
np.asarray(mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [46]:
# checking if matrix is a subclass of array

issubclass(np.matrix,np.ndarray)

True

In [47]:
issubclass(np.ndarray,np.matrix)

False

#### Shallow and Deep copy in array

In [48]:
arr

array([1, 2, 3, 4, 5])

In [49]:
a = arr
a

array([1, 2, 3, 4, 5])

In [50]:
b = np.copy(arr)
b

array([1, 2, 3, 4, 5])

In [51]:
# let's modify a value in arr

arr[-1] = 10 #changing last value to 10
arr

array([ 1,  2,  3,  4, 10])

In [52]:
# print a
a

array([ 1,  2,  3,  4, 10])

Changes reflect in a due to the nature of shallow copy

Whereas, b doesn't reflect any changes because it has taken a deep copy

In [53]:
b

array([1, 2, 3, 4, 5])

Traversing through an array using for loop

In [54]:
arr2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [55]:
for i in arr2:
    print(i)

[1 2 3]
[4 5 6]
[7 8 9]


np.fromfunction

np.fromfunction generates an array based on the functional logic defined in it.
It constructs the entire array by passing the function to each position of the array.
An example to detail it is below.

In [56]:
np.fromfunction(lambda i,j:i==j,(3,3))

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [57]:
np.fromfunction(lambda i,j:i+j,(3,3))

array([[0., 1., 2.],
       [1., 2., 3.],
       [2., 3., 4.]])

In [58]:
np.fromfunction(lambda i,j:i/j,(3,3))

C:\Users\Nithish.s\AppData\Local\Temp\ipykernel_16720\224034625.py:1: RuntimeWarning: divide by zero encountered in divide
  np.fromfunction(lambda i,j:i/j,(3,3))
C:\Users\Nithish.s\AppData\Local\Temp\ipykernel_16720\224034625.py:1: RuntimeWarning: invalid value encountered in divide
  np.fromfunction(lambda i,j:i/j,(3,3))


array([[nan, 0. , 0. ],
       [inf, 1. , 0.5],
       [inf, 2. , 1. ]])

np.fromiter

In [61]:
gen = (i*i for i in range(5)) 
gen # An ,iterable object is created

<generator object <genexpr> at 0x000001D10493B2A0>

In [62]:
np.fromiter(gen,dtype=int) # The np.fromiter creates an array from the object 

array([ 0,  1,  4,  9, 16])

In [63]:
# re-excute the gen line above to run this
for i in gen:
    print(i)

np.fromstring

In [64]:
np.fromstring('1,4,4,6,6,7,6',sep=",",dtype=int)

array([1, 4, 4, 6, 6, 7, 6])

In [65]:
np.fromstring('1 4 4 6 6 7 6',sep=" ",dtype=complex)

array([1.+0.j, 4.+0.j, 4.+0.j, 6.+0.j, 6.+0.j, 7.+0.j, 6.+0.j])

other arrays that can be generated with in-built feauters of NumPy

In [66]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [67]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [68]:
np.zeros((3,4,3)) # 3  - 4 rows and 3 columns

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [69]:
np.ones(2)

array([1., 1.])

In [70]:
np.ones((5,6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [71]:
np.ones((2,5,6))

array([[[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]]])

In [72]:
np.empty(10) # this generates random data

array([nan,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])

In [73]:
np.empty((2,3,2))

array([[[0.04761905, 0.09090909],
        [0.13043478, 0.16666667],
        [0.2       , 0.23076923]],

       [[0.25925926, 0.28571429],
        [0.31034483, 0.33333333],
        [0.35483871, 0.375     ]]])

In [74]:
np.empty((2,3))

array([[0. , 0. , 1. ],
       [0.5, 2. , 1. ]])

In [75]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [76]:
np.eye(2,5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.]])

In [77]:
# Additional, exercises with linspace
np.linspace(2,4,5)

array([2. , 2.5, 3. , 3.5, 4. ])

In [78]:
np.linspace(2,4,5,endpoint=False) # this eliminates the upper bound

array([2. , 2.4, 2.8, 3.2, 3.6])

In [79]:
np.linspace([1,5],4,endpoint=False)

array([[1.  , 5.  ],
       [1.06, 4.98],
       [1.12, 4.96],
       [1.18, 4.94],
       [1.24, 4.92],
       [1.3 , 4.9 ],
       [1.36, 4.88],
       [1.42, 4.86],
       [1.48, 4.84],
       [1.54, 4.82],
       [1.6 , 4.8 ],
       [1.66, 4.78],
       [1.72, 4.76],
       [1.78, 4.74],
       [1.84, 4.72],
       [1.9 , 4.7 ],
       [1.96, 4.68],
       [2.02, 4.66],
       [2.08, 4.64],
       [2.14, 4.62],
       [2.2 , 4.6 ],
       [2.26, 4.58],
       [2.32, 4.56],
       [2.38, 4.54],
       [2.44, 4.52],
       [2.5 , 4.5 ],
       [2.56, 4.48],
       [2.62, 4.46],
       [2.68, 4.44],
       [2.74, 4.42],
       [2.8 , 4.4 ],
       [2.86, 4.38],
       [2.92, 4.36],
       [2.98, 4.34],
       [3.04, 4.32],
       [3.1 , 4.3 ],
       [3.16, 4.28],
       [3.22, 4.26],
       [3.28, 4.24],
       [3.34, 4.22],
       [3.4 , 4.2 ],
       [3.46, 4.18],
       [3.52, 4.16],
       [3.58, 4.14],
       [3.64, 4.12],
       [3.7 , 4.1 ],
       [3.76, 4.08],
       [3.82,

In [80]:
np.linspace([1,5],4,endpoint=False,axis=1)

array([[1.  , 1.06, 1.12, 1.18, 1.24, 1.3 , 1.36, 1.42, 1.48, 1.54, 1.6 ,
        1.66, 1.72, 1.78, 1.84, 1.9 , 1.96, 2.02, 2.08, 2.14, 2.2 , 2.26,
        2.32, 2.38, 2.44, 2.5 , 2.56, 2.62, 2.68, 2.74, 2.8 , 2.86, 2.92,
        2.98, 3.04, 3.1 , 3.16, 3.22, 3.28, 3.34, 3.4 , 3.46, 3.52, 3.58,
        3.64, 3.7 , 3.76, 3.82, 3.88, 3.94],
       [5.  , 4.98, 4.96, 4.94, 4.92, 4.9 , 4.88, 4.86, 4.84, 4.82, 4.8 ,
        4.78, 4.76, 4.74, 4.72, 4.7 , 4.68, 4.66, 4.64, 4.62, 4.6 , 4.58,
        4.56, 4.54, 4.52, 4.5 , 4.48, 4.46, 4.44, 4.42, 4.4 , 4.38, 4.36,
        4.34, 4.32, 4.3 , 4.28, 4.26, 4.24, 4.22, 4.2 , 4.18, 4.16, 4.14,
        4.12, 4.1 , 4.08, 4.06, 4.04, 4.02]])

In [81]:
# Return number evenly on a log scale
np.logspace(1,5,5)

array([1.e+01, 1.e+02, 1.e+03, 1.e+04, 1.e+05])

In [82]:
np.logspace([1,5],5)

array([[1.00000000e+01, 1.00000000e+05],
       [1.20679264e+01, 1.00000000e+05],
       [1.45634848e+01, 1.00000000e+05],
       [1.75751062e+01, 1.00000000e+05],
       [2.12095089e+01, 1.00000000e+05],
       [2.55954792e+01, 1.00000000e+05],
       [3.08884360e+01, 1.00000000e+05],
       [3.72759372e+01, 1.00000000e+05],
       [4.49843267e+01, 1.00000000e+05],
       [5.42867544e+01, 1.00000000e+05],
       [6.55128557e+01, 1.00000000e+05],
       [7.90604321e+01, 1.00000000e+05],
       [9.54095476e+01, 1.00000000e+05],
       [1.15139540e+02, 1.00000000e+05],
       [1.38949549e+02, 1.00000000e+05],
       [1.67683294e+02, 1.00000000e+05],
       [2.02358965e+02, 1.00000000e+05],
       [2.44205309e+02, 1.00000000e+05],
       [2.94705170e+02, 1.00000000e+05],
       [3.55648031e+02, 1.00000000e+05],
       [4.29193426e+02, 1.00000000e+05],
       [5.17947468e+02, 1.00000000e+05],
       [6.25055193e+02, 1.00000000e+05],
       [7.54312006e+02, 1.00000000e+05],
       [9.102981

In [83]:
log_arr = np.logspace([1,5],5,axis=1)
log_arr

array([[1.00000000e+01, 1.20679264e+01, 1.45634848e+01, 1.75751062e+01,
        2.12095089e+01, 2.55954792e+01, 3.08884360e+01, 3.72759372e+01,
        4.49843267e+01, 5.42867544e+01, 6.55128557e+01, 7.90604321e+01,
        9.54095476e+01, 1.15139540e+02, 1.38949549e+02, 1.67683294e+02,
        2.02358965e+02, 2.44205309e+02, 2.94705170e+02, 3.55648031e+02,
        4.29193426e+02, 5.17947468e+02, 6.25055193e+02, 7.54312006e+02,
        9.10298178e+02, 1.09854114e+03, 1.32571137e+03, 1.59985872e+03,
        1.93069773e+03, 2.32995181e+03, 2.81176870e+03, 3.39322177e+03,
        4.09491506e+03, 4.94171336e+03, 5.96362332e+03, 7.19685673e+03,
        8.68511374e+03, 1.04811313e+04, 1.26485522e+04, 1.52641797e+04,
        1.84206997e+04, 2.22299648e+04, 2.68269580e+04, 3.23745754e+04,
        3.90693994e+04, 4.71486636e+04, 5.68986603e+04, 6.86648845e+04,
        8.28642773e+04, 1.00000000e+05],
       [1.00000000e+05, 1.00000000e+05, 1.00000000e+05, 1.00000000e+05,
        1.00000000e+05,

In [84]:
log_arr.shape

(2, 50)

In [85]:
log_arr.reshape(1,2,50) # 1 row - 2 columns with 50 data points in each column

array([[[1.00000000e+01, 1.20679264e+01, 1.45634848e+01, 1.75751062e+01,
         2.12095089e+01, 2.55954792e+01, 3.08884360e+01, 3.72759372e+01,
         4.49843267e+01, 5.42867544e+01, 6.55128557e+01, 7.90604321e+01,
         9.54095476e+01, 1.15139540e+02, 1.38949549e+02, 1.67683294e+02,
         2.02358965e+02, 2.44205309e+02, 2.94705170e+02, 3.55648031e+02,
         4.29193426e+02, 5.17947468e+02, 6.25055193e+02, 7.54312006e+02,
         9.10298178e+02, 1.09854114e+03, 1.32571137e+03, 1.59985872e+03,
         1.93069773e+03, 2.32995181e+03, 2.81176870e+03, 3.39322177e+03,
         4.09491506e+03, 4.94171336e+03, 5.96362332e+03, 7.19685673e+03,
         8.68511374e+03, 1.04811313e+04, 1.26485522e+04, 1.52641797e+04,
         1.84206997e+04, 2.22299648e+04, 2.68269580e+04, 3.23745754e+04,
         3.90693994e+04, 4.71486636e+04, 5.68986603e+04, 6.86648845e+04,
         8.28642773e+04, 1.00000000e+05],
        [1.00000000e+05, 1.00000000e+05, 1.00000000e+05, 1.00000000e+05,
         

In [86]:
arr

array([ 1,  2,  3,  4, 10])

In [87]:
mat

matrix([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [88]:
mat.T

matrix([[1, 4, 7],
        [2, 5, 8],
        [3, 6, 9]])

In [89]:
arr2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [90]:
arr2.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [91]:
# 1d Transpose
arr.reshape(5,1)

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [10]])

### Swapping

In [92]:
arr2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [93]:
arr2[:,[0,2]] = arr2[:,[2,0]]

In [94]:
arr2

array([[3, 2, 1],
       [6, 5, 4],
       [9, 8, 7]])