##  Table of Content

1. **[One Dimensional Array](#1D)**
2. **[Two Dimensional Array](#2D)**
3. **[Stacking](#Stacking)**
4. **[Splitting](#Splitting)**
5. **[For Loop](#loop)**

**Import the NumPy library before solving the exercises**

In [1]:
import numpy as np

### Let's begin with some hands-on practice exercises

<a id="1D"> </a>
## 1. One Dimensional Array

<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>1. Write a NumPy program to convert a list of numeric values into a one-dimensional NumPy array</b>
                </font>
            </div>
        </td>
    </tr>
</table>

**Use the list given below: (or create your own list)**<br>

    list_temperature = [3.04, 1.65, 5.76, 1.66, 1.54, 4.69, 2.68]

In [2]:
list_temperature = [3.04, 1.65, 5.76, 1.66, 1.54, 4.69, 2.68]
arr1 = np.array(list_temperature)
print(arr1)
print(type(arr1))

[3.04 1.65 5.76 1.66 1.54 4.69 2.68]
<class 'numpy.ndarray'>


<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>2. Create a 1D array of weights of 10 students and retrieve all the weights greater than 68</b>
                </font>
            </div>
        </td>
    </tr>
</table>

**Use the weights given below: (or create your own list)**

    weights = [74.2, 85, 74, 67.9, 52, 70.5, 86, 51.8, 64, 82]

In [3]:
weights = [74.2, 85, 74, 67.9, 52, 70.5, 86, 51.8, 64, 82]
arr_w = np.array(weights)
print('Original Array of weights')
print(arr_w)
print()
print('Array with weights greater than 68')
print(arr_w[arr_w>68])

Original Array of weights
[74.2 85.  74.  67.9 52.  70.5 86.  51.8 64.  82. ]

Array with weights greater than 68
[74.2 85.  74.  70.5 86.  82. ]


<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>3. Write a code to generate 10 random integers between 20 to 40 (Is it possible to generate same random numbers everytime? If yes, describe the function)
                    </b>
                </font>
            </div>
        </td>
    </tr>
</table>

In [4]:
np.random.seed(23)

np.random.randint(low=20,high=40,size=10) 

array([39, 26, 28, 29, 28, 33, 32, 27, 39, 26])

#### Yes, it is possible to generate same set od random numbers everytime with seed function in numpy.

<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>4. Write a program to get the fifth power of the first five positive integers
                    </b>
                </font>
            </div>
        </td>
    </tr>
</table>

In [5]:
np.array(range(1,6))**5

array([   1,   32,  243, 1024, 3125], dtype=int32)

<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>5. Write a program to create an array of all the odd integers from 50 to 100 
                    </b>
                </font>
            </div>
        </td>
    </tr>
</table>

In [6]:
arr2 = np.array(range(50,101))
arr2[arr2%2!=0]

array([51, 53, 55, 57, 59, 61, 63, 65, 67, 69, 71, 73, 75, 77, 79, 81, 83,
       85, 87, 89, 91, 93, 95, 97, 99])

<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>6. Write a program to calculate the sum of each column </b>
                </font>
            </div>
        </td>
    </tr>
</table>

**Use the array given below: (or create your own array)**

    A = [[1, 4, 8], [5, 7, 3], [9, 14, 2]]

In [7]:
A = [[1, 4, 8], [5, 7, 3], [9, 14, 2]]
arr_A = np.array(A)
print(arr_A)
print()
print('Sum of each column')
print(arr_A.sum(axis=0))

[[ 1  4  8]
 [ 5  7  3]
 [ 9 14  2]]

Sum of each column
[15 25 13]


<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>7. Write a code to get the element-wise remainder of an array after division by 8 
                    </b>
                </font>
            </div>
        </td>
    </tr>
</table>

**Use the list given below:**<br>
    
    num = [42, 87, 90, 14, 32, 75, 61, 80, 92]

In [8]:
num = [42, 87, 90, 14, 32, 75, 61, 80, 92]
arr_num = np.array(num)
arr_num%8

array([2, 7, 2, 6, 0, 3, 5, 0, 4], dtype=int32)

<a id="2D"> </a>
## 2. Two Dimensional Array

<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>8. Create a 2D numpy array from a 1D array of 20 elements of your choice. Further, subset the first 5 elements from the second element of a resulting 2D array 
                    </b>
                </font>
            </div>
        </td>
    </tr>
</table>

In [9]:
arr_1d = np.random.randn(20)
arr_1d

array([ 0.56857098, -0.47818389,  1.53194062, -0.44070334, -0.06272943,
        0.36914973,  1.11872163,  0.80399214, -1.84926796,  1.38809014,
       -2.41201527, -0.45175246,  1.17420672,  0.76634838, -0.36181507,
        0.36828877,  0.37715847, -0.28972396,  1.02121961, -0.18266918])

In [10]:
arr_1d.ndim

1

In [11]:
arr_2d = arr_1d.reshape(5,4)
arr_2d

array([[ 0.56857098, -0.47818389,  1.53194062, -0.44070334],
       [-0.06272943,  0.36914973,  1.11872163,  0.80399214],
       [-1.84926796,  1.38809014, -2.41201527, -0.45175246],
       [ 1.17420672,  0.76634838, -0.36181507,  0.36828877],
       [ 0.37715847, -0.28972396,  1.02121961, -0.18266918]])

In [12]:
arr_2d.ndim

2

In [13]:
arr_2d[1,:] 

array([-0.06272943,  0.36914973,  1.11872163,  0.80399214])

<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>9. Write a program to find common values between two arrays 
                    </b>
                </font>
            </div>
        </td>
    </tr>
</table>

**Use the lists given below:**<br>

    prices_monday = [10, 30, 50, 60, 90]

    prices_tuesday = [50, 20, 80, 125, 10, 70]

In [14]:
prices_monday = [10, 30, 50, 60, 90]

prices_tuesday = [50, 20, 80, 125, 10, 70]

arr_m = np.array(prices_monday)
arr_t = np.array(prices_tuesday)

np.intersect1d(arr_m,arr_t)

array([10, 50])

<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>10. Write a program to find BMI of the patients whose height and weight is provided in the list given below 
                    </b>
                </font>
            </div>
        </td>
    </tr>
</table>

**Use the lists given below:**<br>

    list of weights (in kg)
    weights = [57, 69, 54, 65 ,71, 62, 56]

    list of heights (in m)
    heights = [1.59, 1.75, 1.66, 1.74, 1.64, 1.72, 1.53] 

In [15]:
weights = [57, 69, 54, 65 ,71, 62, 56]

heights = [1.59, 1.75, 1.66, 1.74, 1.64, 1.72, 1.53] 

def bmi_cal(weight,height):
    return np.round(np.array(weights)/np.array(heights)**2,2)

In [16]:
bmi_cal(weights,heights)

array([22.55, 22.53, 19.6 , 21.47, 26.4 , 20.96, 23.92])

<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>11. Write a program to add a new column ([5,7]) at the last position in the array given below 
                    </b>
                </font>
            </div>
        </td>
    </tr>
</table>

**Use the array given below:**

    array1 = [[[3, 4], [8, 2],[5, 9]]]

In [17]:
array1 = [[[3, 4], [8, 2],[5, 9]]]
arr_1 = np.array(array1)
print(arr_1)
print('Shape:',arr_1.shape)
print('Dimension:',arr_1.ndim)

[[[3 4]
  [8 2]
  [5 9]]]
Shape: (1, 3, 2)
Dimension: 3


In [18]:
arr_1 = np.append(arr_1,[5,7]).reshape(1,4,2) # 2 represents the elements in sub array
print(arr_1)
print('Shape:',arr_1.shape)
print('Dimension:',arr_1.ndim)

[[[3 4]
  [8 2]
  [5 9]
  [5 7]]]
Shape: (1, 4, 2)
Dimension: 3


<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>12. Write a code to print the identity matrix of order 5</b>
                </font>
            </div>
        </td>
    </tr>
</table>

In [19]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>13. Write a program to transpose a matrix 
                    </b>
                </font>
            </div>
        </td>
    </tr>
</table>

**Use the matrix given below:**
    
    M = [[15, 17, 45, 56], [7, 42, 15, 63], [54, 3, 61, 41], [0, 87, 16, 20]]

In [20]:
M = [[15, 17, 45, 56], [7, 42, 15, 63], [54, 3, 61, 41], [0, 87, 16, 20]]
arr_M = np.array(M)
print('Original')
print(arr_M)
print()
print('Transposed')
print(arr_M.T)

Original
[[15 17 45 56]
 [ 7 42 15 63]
 [54  3 61 41]
 [ 0 87 16 20]]

Transposed
[[15  7 54  0]
 [17 42  3 87]
 [45 15 61 16]
 [56 63 41 20]]


<a id="Stacking"> </a>
## 3. Stacking

<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>14. Write a program to combine the two arrays vertically</b>
                </font>
            </div>
        </td>
    </tr>
</table>

**Use the arrays given below: (or create your own array)**<br>

    A1 = [[5, 9], [7, 6]]

    A2 = [[8,-7], [0,4]]

Combine the array A2 with A1

In [21]:
A1 = [[5, 9], [7, 6]]
A2 = [[8,-7], [0,4]]
arr_A1 = np.array(A1)
arr_A2 = np.array(A2)

In [22]:
np.vstack([arr_A1,arr_A2])

array([[ 5,  9],
       [ 7,  6],
       [ 8, -7],
       [ 0,  4]])

<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>15. Write a code to combine the two arrays horizontally</b>
                </font>
            </div>
        </td>
    </tr>
</table>

**Use the arrays given below: (or create your own array)**

    A1 = [[-81, 75, 40], [27, 67, 52]]

    A2 = [[15, 54], [39, 56]]

Combine the array A2 with A1

In [23]:
A1 = [[-81, 75, 40], [27, 67, 52]]
A2 = [[15, 54], [39, 56]]
arr_A1_1 = np.array(A1)
arr_A2_1 = np.array(A2)

np.hstack([arr_A1_1,arr_A2_1])

array([[-81,  75,  40,  15,  54],
       [ 27,  67,  52,  39,  56]])

<a id="Splitting"> </a>
## 4. Splitting

<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>16. Write a code to divide the array into three sub-arrays containing
                       equal number of rows</b>
                </font>
            </div>
        </td>
    </tr>
</table>

**Use the array given below:**<br>

    A = [[4, 7], [2, -3], [8, 1], [0, 9], [5,-1], [8, 3]]

In [24]:
A = [[4, 7], [2, -3], [8, 1], [0, 9], [5,-1], [8, 3]]
arr_A = np.array(A)
print(arr_A)
print('Shape:',arr_A.shape)
print('Dimension:',arr_A.ndim)

[[ 4  7]
 [ 2 -3]
 [ 8  1]
 [ 0  9]
 [ 5 -1]
 [ 8  3]]
Shape: (6, 2)
Dimension: 2


In [25]:
arr_A.reshape(3,4)

array([[ 4,  7,  2, -3],
       [ 8,  1,  0,  9],
       [ 5, -1,  8,  3]])

In [26]:
arr_A_split = np.vsplit(arr_A,3)
print('Array 1')
print(arr_A_split[0])
print()
print('Array 2')
print(arr_A_split[1])
print()
print('Array 3')
print(arr_A_split[2])

Array 1
[[ 4  7]
 [ 2 -3]]

Array 2
[[8 1]
 [0 9]]

Array 3
[[ 5 -1]
 [ 8  3]]


<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>17. Write a program to divide the array into two sub-arrays containing equal number of columns
                    </b>
                </font>
            </div>
        </td>
    </tr>
</table>

**Use the array given below:**

    B = [[8, 7, 0, 9], [2, -3, 5, 10], [8, 5, -1,3]]

In [27]:
B = [[8, 7, 0, 9], [2, -3, 5, 10], [8, 5, -1,3]]
arr_B = np.array(B)
print(arr_B)
print('Shape:',arr_B.shape)
print('Dimension:',arr_B.ndim)

[[ 8  7  0  9]
 [ 2 -3  5 10]
 [ 8  5 -1  3]]
Shape: (3, 4)
Dimension: 2


In [28]:
np.hsplit(arr_B,2)

[array([[ 8,  7],
        [ 2, -3],
        [ 8,  5]]),
 array([[ 0,  9],
        [ 5, 10],
        [-1,  3]])]

<a id="loop"> </a>
## 5. For Loop

<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>18. Write a program to perform one-to-one mapping of the two lists</b>
                </font>
            </div>
        </td>
    </tr>
</table>

**Use the lists given below: (or create your own lists)**<br>

    L1 = [45, 67, 56, 71, 54, 62, 56]

    L2 = [21, 52, 64, 10, 49, 74, 26]

In [29]:
L1 = [45, 67, 56, 71, 54, 62, 56]
L2 = [21, 52, 64, 10, 49, 74, 26]
L1 = np.array(L1)
L2 = np.array(L2)
for i,j in zip(L1,L2):
    print(i,j)

45 21
67 52
56 64
71 10
54 49
62 74
56 26


<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>19. Define a for loop to apply the function (2x-1)/(x+5) on every element of an array </b>
                </font>
            </div>
        </td>
    </tr>
</table>

**Use the list given below:**
    
    numbers = [6, 5, 3, 15]

In [30]:
numbers = [6,5,3,15]
num_arr = np.array(numbers)
def calc_fn(inpt_arr):
    result = []
    for x in inpt_arr:
        result.append((2*x-1)/(x+5))
        
    return np.array(result)

In [31]:
calc_fn(num_arr)

array([1.   , 0.9  , 0.625, 1.45 ])

<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>20. Create an identity matrix with n dimensions (take input from the user). Fill the diagonals of that matrix with the multiples of the number provided by the user; take another input from the user. </b>
                </font>
            </div>
        </td>
    </tr>
</table>

In [32]:
dim = int(input("Enter dimension"))
multi = int(input("Enter multiple"))

lst = [multi*i for i in range(1,dim+1)]

id_arr = np.eye(dim)
id_arr

Enter dimension5
Enter multiple5


array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [33]:
for j in range(0,len(id_arr)):
    id_arr[j][j] = lst[j]
    id_arr[len(id_arr)-1-j][j] = lst[j]

In [34]:
id_arr # Resultant output

array([[ 5.,  0.,  0.,  0., 25.],
       [ 0., 10.,  0., 20.,  0.],
       [ 0.,  0., 15.,  0.,  0.],
       [ 0., 10.,  0., 20.,  0.],
       [ 5.,  0.,  0.,  0., 25.]])