# Numpy Exercise - 01

-----------

In [1]:
import numpy as np

**(1).Create a 1D array with 10 values in it and then convert the 1D array to 2D array ?**

In [2]:
arr1 = np.random.randn(10)
print('Array 1:\n',arr1)
print(arr1)
print('Dimension of Array 1:',arr1.ndim)

Array 1:
 [ 0.01180793  2.15022849 -0.33455891 -1.40055384 -0.38459669 -0.6847496
  2.09662671  1.2645252  -1.05869897 -0.70992622]
[ 0.01180793  2.15022849 -0.33455891 -1.40055384 -0.38459669 -0.6847496
  2.09662671  1.2645252  -1.05869897 -0.70992622]
Dimension of Array 1: 1


In [3]:
arr2 = arr1.reshape(5,2)
print('Array 2:\n',arr2)
print('Dimension of Array 2:',arr2.ndim)

Array 2:
 [[ 0.01180793  2.15022849]
 [-0.33455891 -1.40055384]
 [-0.38459669 -0.6847496 ]
 [ 2.09662671  1.2645252 ]
 [-1.05869897 -0.70992622]]
Dimension of Array 2: 2


-------------------------------------------------------------

**(2).Print or show only 3 decimal places of the numpy array `random_arr`**

In [4]:
random_arr = np.random.randn(10)
np.round(random_arr,3)

array([-0.366,  0.002, -0.176,  0.797,  0.518, -1.584, -0.366,  0.795,
        0.526,  1.906])

----------------------------------

**(3).The number of items printed to be limit in python numpy array a to a maximum of 6 elements.**

   
     Intake : x = np.arange(15)
               array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])
               
     Result : ([ 0,  1,  2, ..., 12, 13, 14])

In [5]:
x = np.arange(15)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

---------------------

**(4). Take two arrays  `x` and `y` and Stack the `x` and `y` arrays Horizontal.**


    Intake:
                x = np.arange(10).reshape(2,-1)

                y = np.repeat(1, 10).reshape(2,-1)

 
    
    Result:       ([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
                   [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

In [6]:
x = np.arange(10).reshape(2,-1)
y = np.repeat(1, 10).reshape(2,-1)
print('Array x:\n',x)
print()
print('Array y:\n',y)

Array x:
 [[0 1 2 3 4]
 [5 6 7 8 9]]

Array y:
 [[1 1 1 1 1]
 [1 1 1 1 1]]


In [7]:
np.hstack(tup=(x,y))

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

In [8]:
# even a list can be passed to get the output
np.hstack([x,y])

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

----------------------

**(5). Consider the given array's and print the values which are common in both the arrays.**
    
    
    Intake: 
   
        x = np.array([1,2,3,2,3,4,3,4,5,6])
        y = np.array([7,2,10,2,7,4,9,4,9,8])
 
    Results:
        
         ([2, 4])
            
    

In [9]:
x = np.array([1,2,3,2,3,4,3,4,5,6])
y = np.array([7,2,10,2,7,4,9,4,9,8])
print('Common elements between x and y are:')
print(np.intersect1d(x,y))

Common elements between x and y are:
[2 4]


---------------------

**(6). There are two array x and y ,drop the items in `X` which already exist in `Y`.**

   
    INTAKE:
     x = np.array([1,2,3,4,5])
     y = np.array([5,6,7,8,9])
    
    
    RESULT:
     ([1,2,3,4])
        
    

In [10]:
x = np.array([1,2,3,4,5])
y = np.array([5,6,7,8,9])

np.array(list(filter(lambda i:i not in y,x)))

array([1, 2, 3, 4])

--------------------------

**(7). Reverse the rows of a 2D array.**


    Intake : X = np.arange(9).reshape(3,3)
    
    Result :      ([[6, 7, 8],
                    [3, 4, 5],
                    [0, 1, 2]])

In [11]:
X = np.arange(9).reshape(3,3)
X

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [12]:
print('Reversed array')
np.flip(X,axis=0)

Reversed array


array([[6, 7, 8],
       [3, 4, 5],
       [0, 1, 2]])

----------------------

**(8). Reverse the columns of a 2D array.**

    Intake : X = np.arange(9).reshape(3,3)
    
    Result :     ([[2, 1, 0],
                   [5, 4, 3],
                   [8, 7, 6]])


In [13]:
X = np.arange(9).reshape(3,3)
X

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [14]:
np.flip(X,axis=1)

array([[2, 1, 0],
       [5, 4, 3],
       [8, 7, 6]])

---------------------

**(9). Print the ranks for the given numeric array `x`.**
 
   
    Intake:
    np.random.seed(10)
    x = np.random.randint(20, size=10)
    print(x)
    [ 9  4 15  0 17 16 17  8  9  0]
    
    
    Result:
    [4 2 6 0 8 7 9 3 5 1]
    

In [15]:
np.random.seed(10)
x = np.random.randint(20, size=10)
x

array([ 9,  4, 15,  0, 17, 16, 17,  8,  9,  0])

In [16]:
ord = x.argsort()
ord.argsort()

array([4, 2, 6, 0, 8, 7, 9, 3, 5, 1], dtype=int64)

--------------------

**(10). For the given numeric array print the rank array with same shape of numeric array.**


    Intake:
    np.random.seed(10)
    x = np.random.randint(20, size=[2,5])
    print(a)
    [[ 9  4 15  0 17]
    [16 17  8  9  0]]
    
    Result:
    [[4 2 6 0 8]
    [7 9 3 5 1]]

In [17]:
np.random.seed(10)
a = np.random.randint(20, size=[2,5])
print(a)

[[ 9  4 15  0 17]
 [16 17  8  9  0]]


In [18]:
ord = a.flatten().argsort()
print('ord',ord)
rnk = ord.argsort()
print('rnk',rnk)
rnk.reshape(2,5)

ord [3 9 1 7 0 8 2 5 4 6]
rnk [4 2 6 0 8 7 9 3 5 1]


array([[4, 2, 6, 0, 8],
       [7, 9, 3, 5, 1]], dtype=int64)

--------------------------------

**(11). Subtract the 1d array y_1d from the 2d array x_2d, such that each item of y_1d subtracts from respective row of x_2d.**
    
    Intake:
    x_2d = np.array([[3,3,3],[4,4,4],[5,5,5]])
    y_1d = np.array([1,2,3])
    
    Result:
     [[2 2 2]
     [2 2 2]
     [2 2 2]]

In [19]:
x_2d = np.array([[3,3,3],[4,4,4],[5,5,5]])
y_1d = np.array([1,2,3])
print('x_2d:\n',x_2d)
print()
print('y_1d:\n',y_1d)

x_2d:
 [[3 3 3]
 [4 4 4]
 [5 5 5]]

y_1d:
 [1 2 3]


In [20]:
print(x_2d-y_1d[:,None])

[[2 2 2]
 [2 2 2]
 [2 2 2]]


In [21]:
# or

In [22]:
print(x_2d-y_1d.reshape(3,1))

[[2 2 2]
 [2 2 2]
 [2 2 2]]


----------------

-------------------